---
# Encrypted variables - use ansible-vault to encrypt this file
# ansible-vault encrypt inventory/group_vars/vault.yml
# ansible-vault edit inventory/group_vars/vault.yml

vault_admin_password: "your_admin_password"
vault_enable_password: "your_enable_password"
vault_bgp_password: "your_bgp_password"
